# Generated by Django 4.0.5 on 2022-06-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_museum', '0002_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
