# Generated by Django 4.0.5 on 2022-06-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_museum', '0003_alter_medium_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('adress', models.TextField(max_length=1000)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('image', models.ImageField(null=True, upload_to='museums')),
            ],
        ),
    ]
